version: '3.5'

services:
  database:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: [ default ]
    ports: [ '5435:5432' ]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  php:
    # Build command: docker build -t funchy/x15-platform-api:8.0-v10 . --target development
    # If changes are required use your own docker hub account and push it there.
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks: [ default ]
    environment:
      XDEBUG_MODE: debug # or `profile`
      XDEBUG_CONFIG: client_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=${APP_HOST}
      SSH_AUTH_SOCK: /ssh-agent
    depends_on:
      - database

  server:
    image: nginx:1.21
    env_file: .env
    volumes:
      - ./docker/site-default-local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certificates/acd-certificate.crt:/cert/server.crt
      - ./docker/certificates/acd-certificate.key:/cert/server.key
    ports: [ '8091:80', '8092:443' ]
    networks:
      default:
        aliases:
          - ${APP_HOST}
    depends_on:
      - php

volumes:
  postgres:

networks:
  default:
    driver: bridge
